### ISSUE TITLE
Function run, get billing costs

### ISSUE THREAD

**Issue by ahmed-mohamed-sn** [modal-labs/modal-examples#177]
Hi modal team,

First of all thank you for such an amazing product,  I am wondering if it is possible to retrieve the billing costs for a specific function run. If not, is it planned?

**Comment by luiscape** [comment]
Hi @ahmed-mohamed-sn, it is currently not possible to retrieve costs at the function level. It's currently in our backlog.

Would you tell us a bit more about how you would like to use that info? We are figuring out good use-cases.

**Comment by luiscape** [comment]
Got it. That makes sense. I'll post to this issue when updates are available.

**Comment by ahmed-mohamed-sn** [comment]
Thank you!

**Comment by ahmed-mohamed-sn** [comment]
Hi @luiscape, I was wondering if there is an update regarding this issue. I am currently using the task duration time as an approximation but it will be great to have the actual cost.

**Comment by kning** [comment]
this is solved right? you can see cost by function in the usage billing tab

**Comment by luiscape** [comment]
This isn't implemented yet but it's something we are tracking internally. I think it's a good idea to close this ticket in favor of our internal tracking.

**Comment by kning** [comment]
ah right i see i misread the use case, my bad.
