### ISSUE TITLE
Modal lookup for class function

### ISSUE THREAD

**Issue by hitz02** [modal-labs/modal-examples#227]
Hi Team,

How can we do a modal lookup for a stub function defined within a class?

I am referring to your HuggingFace batch inference example - https://modal.com/docs/guide/ex/batch_inference_using_huggingface

Any help is appreciated.

Thanks!

**Comment by erikbern** [comment]
I believe you can look it up using `ClassName.function_name`

**Comment by hitz02** [comment]
Thanks @erikbern this works!
