### ISSUE TITLE
Error with Getting started example - "Can't serialize object <modal.functions._FunctionHandle"

### ISSUE THREAD

**Issue by pawarbi** [modal-labs/modal-examples#228]
I installed Modal in Jupyter Notebook, Win 10 machine and ran the following code: 

`!pip install modal-client`
`!modal token new`

I was prompted to sign in a new browser, got confetti. 
![image](https://user-images.githubusercontent.com/62612119/220393582-88bd107c-01dc-4888-a740-ad2bb714c73e.png)

`
import modal

stub = modal.Stub("example-get-started")

@stub.function
def square(x):
    print("This code is running on a remote worker!")
    return x**2

@stub.local_entrypoint
def main():
    print("the square is", square.call(42))
`
Received below error message: 

![image](https://user-images.githubusercontent.com/62612119/220393085-e5dbe14f-75a2-4485-b456-843c79747e43.png)

Any idea what could be causing it ? Thanks.

**Comment by erikbern** [comment]
Not entirely sure what's the issue, but Modal has some issues in Notebooks right now that causes issues like that in several situations. Are you able to run it as a script?

**Comment by thundergolfer** [comment]
Will close this issue as stale. We've fixed some function serialization issues in the past month or so, so this should be working fine. If there's still a problem we can re-open.
