### ISSUE TITLE
Download/Export function for the 'whisper_pod_transcriber' instance?

### ISSUE THREAD

**Issue by tonyho** [modal-labs/modal-examples#240]
The 'https://modal-labs--whisper-pod-transcriber-fastapi-app.modal.run/#/' is wonderful, but it only shows the transcript in webpage. Is there any plan to add the download function to it to let users download the srt format transcripts?

**Comment by gagglepod** [comment]
Did you get it to run locally or on Modal Server? I'm still trying to figure out where the Podchaser Keys go.

To add to your comment -- I would like to be able to make an API call to this and have a JSON and SRT file returned in a Cloud Function too.

**Comment by thundergolfer** [comment]
Hey @tonyho, at the moment no feature additions are planned for this demo app, but contributions are welcome :)
