### ISSUE TITLE
`pip_install` from public github repo

### ISSUE THREAD

**Issue by JonathanRayner** [modal-labs/modal-examples#295]
Is it possible to `pip_install` from a public github repo? It seems like it should be the same syntax as a `requirements.txt` but this hasn't worked for me.

**Comment by erikbern** [comment]
It's definitely possible – see https://github.com/modal-labs/modal-examples/blob/main/06_gpu_and_ml/alpaca/alpaca_lora.py#L35

you might have to `.apt_install("git")` for it to work
