### ISSUE TITLE
removal of a shared volume

### ISSUE THREAD

**Issue by rustagiadi95** [modal-labs/modal-examples#307]
Hi all, 

is there any way to remove a shared volume?

**Comment by thundergolfer** [comment]
Thanks for the question.

Yes, a shared volume will show up in the apps view on the dashboard. It's unintuitive, but going to the app page of a volume and hitting the 'trash' icon on it will stop the volume and delete its data.

<kbd>
<img width="73" alt="image" src="https://user-images.githubusercontent.com/12058921/236009051-01ceaeab-b69a-4b90-84ad-94c52b12f449.png">
</<kbd>

**Comment by rustagiadi95** [comment]
Hi I would like to reopen this issue on the account that modal is prompting me before deploying a modal function saying that this function already exists on a shared volume, but when the shared volumes are listed there is none.

Please help, thanks.
