### ISSUE TITLE
pip3 installation in image

### ISSUE THREAD

**Issue by rustagiadi95** [modal-labs/modal-examples#309]
while creating a container Image, how to install python3 packages?

**Comment by luiscape** [comment]
Hello @rustagiadi95, here's a few ways to install Python dependencies:

- [pip_install](https://modal.com/docs/reference/modal.Image#pip_install) -- to install dependencies individually; example:

```python
import modal

image = (
    modal.Image.debian_slim()
        .pip_install("transformers",  "torch")
)
stub = modal.Stub("my-app", image=image)
```

- [pip_install_from_requirements](https://modal.com/docs/reference/modal.Image#pip_install_from_requirements): install dependencies from a local `requirements.txt` file; example:

```python
import modal

image = (
    modal.Image.debian_slim()
        .pip_install_from_requirements("requirements.txt")
)
stub = modal.Stub("my-app", image=image)
```

There are many more ways here: https://modal.com/docs/reference/modal.Image

Let me know if that helps.

**Comment by rustagiadi95** [comment]
This works, thanks.
