### ISSUE TITLE
App/Stub URL

### ISSUE THREAD

**Issue by ted-dunstone** [modal-labs/modal-examples#346]
I really like the intent of the modal framework, however I cannot figure out how to determine the url of an app that has been started like:

> modal serve modal_start.py

I've looked at the docs that state about the url construction include the ```https://[user-id]--[stub_name]-[function_name].modal.run```

But no combination seems to work for me. Couldn't the public url be output on the command line - or via another tool or on the dashboard. 

Any help gratefully received.

Thanks.

**Comment by thundergolfer** [comment]
Closing this issue as solved 🙂
