### ISSUE TITLE
nfs model upload timeout

### ISSUE THREAD

**Issue by haiderasad** [modal-labs/modal-examples#401]
having timeout issue when uploading large model on modal nfs put vol_name, any workaround on this?

**Comment by luiscape** [comment]
Hi @haiderasad, could you share more details in our [Slack channel](https://join.slack.com/t/modalbetatesters/shared_invite/zt-21l6yi28l-~LVZlMt4j2HYTvseAlBbDw)? It's easier for us to help there.
