### ISSUE TITLE
youtube_face_detection.py is failing

### ISSUE THREAD

**Issue by ekzhang** [modal-labs/modal-examples#405]
Due to the issue described here: https://github.com/pytube/pytube/issues/1768

It looks like YouTube has changed their backend API.

**Comment by ekzhang** [comment]
Okay there are forks that fix this

**Comment by Letscat** [comment]
> Okay there are forks that fix this

Sorry to ask you this, but where can i find such a fork? i dont see anything mentioned on the current issues?
