### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by ted-dunstone** [modal-labs/modal-examples#407]
Is there any documented process by which I can have a modal container running, for instance, MongoDB and then connect this to another modal python file running in a separate container. 

To do this I need to know the url or IP of the instance running the DB. I imagine this might be done using a Dockerfile but I was wondering if this is supported through the modal api?

**Comment by erikbern** [comment]
Modal isn't really meant for running things with persistent state. It's better that you run this outside of Modal and connect to it from Modal

**Comment by thundergolfer** [comment]
Closing as answered 🙂
