### ISSUE TITLE
text_generation_inference.py - Function' object has no attribute 'remote'

### ISSUE THREAD

**Issue by edanuff** [modal-labs/modal-examples#418]
I'm trying to use the text_generation_inference.py example and getting an AttributeError: 'Function' object has no attribute 'remote'

future: <Task finished name='Task-231' coro=<FastAPI.__call__() done, defined at /opt/conda/lib/python3.9/site-packages/fastapi/applications.py:267> exception=AttributeError("'Function' object has no attribute 'remote'")>
Traceback (most recent call last):

**Comment by luiscape** [comment]
Hi @edanuff, can you update to the latest modal client:

```
pip install modal --upgrade
```

Also, could you join our [Beta Testers Slack channel](https://modalbetatesters.slack.com/ssb/redirect)? We're a lot faster with support questions there.
