### ISSUE TITLE
TGI_inference only allowed 40ram for A100

### ISSUE THREAD

**Issue by PCaesar18** [modal-labs/modal-examples#436]
Hi there!

I was experimenting and trying out the new text-generation-inference example/tutorial. The GPU config states to use 2 80ram A100 gpu's but Modal seems to only allow 20 and 40?

Awesome product though and really enjoying playing around!
Best,
Caesar

**Comment by PCaesar18** [comment]
To add to this :) : With multiple examples i've been getting an AttributeError with
`AttributeError: type object 'Image' has no attribute 'from_registry' ` 

I've reinstalled modal but seems to continue failing here

**Comment by erikbern** [comment]
Hi – are you using the latest client version? You might have to upgrade. `pip install --force-reinstall modal`

**Comment by PCaesar18** [comment]
Hi erik, 
Cheers that seems to have quickly resolved the problem. Many thnx!
~Caesar

**Comment by erikbern** [comment]
Is it working now? Sorry I didn't get a chance to look at this.
