### ISSUE TITLE
combining injob queue and model loading class

### ISSUE THREAD

**Issue by haiderasad** [modal-labs/modal-examples#453]
hey is there any way we can set up a ML web app API utilizing the injob queue and model loading instance such that that when a API call comes a job id is returned , this job id  initializes a model class in which a ML model is loaded into memory and utilized, now if another API call comes within this moment it utilizes the same initiated model rather than loading another model.

**Comment by thundergolfer** [comment]
Hey @haiderasad could this question be redirected to our community Slack? I think it's better to have ideas discussion there and leave these Github Issues for bugs or other problems 🙂
