### ISSUE TITLE
depreciated whisper link in pod transciber

### ISSUE THREAD

**Issue by haiderasad** [modal-labs/modal-examples#459]
hey the link used in  [pod_transcriber](https://github.com/modal-labs/modal-examples/blob/main/06_gpu_and_ml/openai_whisper/pod_transcriber/app/main.py
)
has a depreciated
```
 pip_install(
        "https://github.com/openai/whisper/archive/9f70a352f9f8630ab3aa0d06af5cb9532bd8c21d.tar.gz",
```

which gives error while transcribing audios ,so instead to installing from this you can simply use 

```
pip_install(
        "git+https://github.com/openai/whisper.git",
```

which is working perfectly

**Comment by rachelspark** [comment]
Thanks for pointing this out! Updated example :)
