### ISSUE TITLE
pod transcriber torchaudio version

### ISSUE THREAD

**Issue by kayleegeorge** [modal-labs/modal-examples#462]
[error] When I locally served the pod transcriber example, the current pip install torchaudio version gives error

```
ERROR: Could not find a version that satisfies the requirement torchaudio==0.12.1 (from versions: 2.0.0, 2.0.1, 2.0.2, 2.1.0)
ERROR: No matching distribution found for torchaudio==0.12.1
```

[fix] Fixed by changing "torchaudio==0.12.1" to "torchaudio==2.1.0" (latest version) in main.py, line 37

https://modal-labs--whisper-pod-transcriber-fastapi-app.modal.run/ is also down right now, not sure if that's related to this error or not.

**Comment by rachelspark** [comment]
Thanks for pointing this out! Updated example :)
