### ISSUE TITLE
Huggingface Token

### ISSUE THREAD

**Issue by rarhs** [modal-labs/modal-examples#482]
Created `huggingface-secrets` at: `https://modal.com/secrets`

Executed the below commands in the CLI:

`export HUGGINGFACE_TOKEN=huggingface-secrets`
`git clone https://github.com/modal-labs/modal-examples`
`cd modal-examples`
`modal run 06_gpu_and_ml/vllm_inference.py`

got the below error:

`NotFoundError: No secret named huggingface - you can add secrets to your account at https://modal.com/secrets`

**Comment by erikbern** [comment]
@rarhs you need to go create it in the web URL – it's not enough to export the env var!
