### ISSUE TITLE
How are you meant to use from_dockerfile?

### ISSUE THREAD

**Issue by spookyuser** [modal-labs/modal-examples#494]
So i love modal, but i'm using pipenv and so can't use the pip install/poetry install functions, i've experimented with using a few run commands like, copying the pipfiles, then pipenv installing them, but they seem to run everytime i deploy even if i haven't changed either file, but anyway those do technically work but it just takes forever bc it installs every python dependency every time, also i would prefer to be able to specify stuff in the dockerfile anyway. 

If i just do from_dockerfile with a dockerfile like such

```
FROM python:3.11.5-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install pipenv

WORKDIR /app
COPY Pipfile Pipfile.lock /app/

RUN pipenv install --categories='packages cluster' --deploy --system

COPY . /app/
```

That part works but i notice that there's a second step that happens after this where pip installs modal requirements, and after that all of my fastapi stuff breaks, so right now i have just literally added a pipenv comand to install over them at the end and that does work

```
image = modal.Image.from_dockerfile(
    "modal.Dockerfile", context_mount=assets
).run_commands("pipenv install --categories='packages cluster' --deploy --system")
```

But this feels so inelegant? Just wondering how you'd recommend i do this, thanks!

**Comment by erikbern** [comment]
Yeah the problem right now is that Modal has its own set of dependencies that we install on top of any Dockerfile

What exactly breaks?

We've been thinking about making Modal and all its dependencies a self-contained Python executable, which might simplify things a bit!

**Comment by spookyuser** [comment]
Yes that would be great! I can't remember exactly what it was i think there was a pydantic conflict somewhere, how come it doesn't happen if i do the run_commands?
