### ISSUE TITLE
Enhancement: Improve the RAG example using Modal's docs

### ISSUE THREAD

**Issue by feliks912** [modal-labs/modal-examples#523]
Hands down one of the best things I've used. Endless possibilities and surprisingly user-friendly.

**It's so easy to use and distribute it's amazing. I've been playing with it for a few days and am already integrating cloud storage, and local file conversion with CUDA support, transcription, and LLMs.**

I'm very spoiled due to ChatGPT handling a billion libraries but not this one.

Yesterday's hydration error got me to suggest an improved RAG implementation. It was my very first time dealing with this technology and the solution was nowhere to be found. It would be great to get a complex, permutable example on demand.

**I humbly suggest adding Modal's documentation and GitHub examples to the RAG guide.**

Using it in this way could improve the speed of development for newcomers, and lower compute costs during debugging.

Thank you for your consideration. Best of Luck!

**Comment by thundergolfer** [comment]
Hey @feliks912, thanks for the positive feedback 🙂 

I think I'm missing something though. What's the RAG guide and RAG example exactly? 😄. Do you have a link?

**Comment by feliks912** [comment]
Hey, sorry for answering so late. I've looked at examples and was sworn to have seen one. Berenstein bears for a few days straight, then I found it.

It's the LangChain example, QA with LangChain
https://modal.com/docs/examples/potus_speech_qanda

**Comment by thundergolfer** [comment]
Ah yes, that example is pretty old and simple. So you think we should improve the example so that it can perform RAG on Modal's docs? If so, yeah that's a great idea! we really should have already gotten around to doing this. 

Do you think using LangChain is preferable? It could be a separate example that doesn't necessarily use LangChain.
