### ISSUE TITLE
Fast inference with vLLM (Mixtral 8x7B) example

### ISSUE THREAD

**Issue by lexara-prime-ai** [modal-labs/modal-examples#546]
I have tried running this example a few times but I keep running into the following error:

`
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 346, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 575, in call_function_async
    enter_res = enter_method()
  File "/root/vllm.py", line 91, in __enter__
    from vllm.engine.arg_utils import AsyncEngineArgs
ModuleNotFoundError: No module named 'vllm.engine'; 'vllm' is not a package
Runner failed with exception: ModuleNotFoundError("No module named 'vllm.engine'; 'vllm' is not a package")
Stopping app - uncaught exception raised locally: ModuleNotFoundError("No module named 'vllm.engine'; 'vllm' is not a package").

ModuleNotFoundError: No module named 'vllm.engine'; 'vllm' is not a package
`

Should vllm be installed locally?

Shouldn't the script be executed within modal cloud's container instances?

Thank you for your time.

**Comment by luiscape** [comment]
Hi @lexara-prime-ai, what's the name of the local Python script you are running? This can happen if the script is called `vllm.py`. Can you rename the script and try again if that's the case?

**Comment by lexara-prime-ai** [comment]
@luiscape I changed the name to something else and it worked. I tried running it a couple of times, but all runs after the first one seem to fail even though I haven't altered the example's source code. Could you please provide some insight, thanks!

**Comment by luiscape** [comment]
Yes. Can you send me the stack trace via our support Slack ([link](https://join.slack.com/t/modallabscommunity/shared_invite/zt-28c8vav1f-9fa5v6XZa3Wx_DrxR9Gk4g))?
