### ISSUE TITLE
Is it possible to run an application for photogrammetry (creating 3D models from images)?

### ISSUE THREAD

**Issue by DmitryPor** [modal-labs/modal-examples#551]
Is it possible to run an application for photogrammetry (creating 3D models from images)? For example, I use Agisoft Metashape, they have a client for Linux.

**Comment by luiscape** [comment]
Yes, that should be possible. Let me know if you run into any errors. 

Not the same use-case but our [Blender example](https://modal.com/docs/examples/blender_video#render-a-video-with-blender-on-gpus) can give you a sense of how something like that would work.

**Comment by yosun** [comment]
curious how you would install it on modal? 

another photogrammetry pipeline that is fairly well supported uses m1 macs (which are avail on aws ec2)  https://developer.apple.com/augmented-reality/object-capture/

**Comment by luiscape** [comment]
> curious how you would install it on modal?

I would first look for Linux software and / or examples that use a Docker container. Changes are those can run on Modal.
