### ISSUE TITLE
how to imports packages from a cloned repo in modal?

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [modal-labs/modal-examples#554]
```
import sys
import modal
from typing import Dict
from modal import Image,Volume, web_endpoint, enter, method

project_image = (Image.debian_slim(python_version="3.10")
                .apt_install("git","ffmpeg","libsm6","libxext6")
				.pip_install_from_requirements("requirements.txt")
    			.run_commands("git clone https://github.com/Arslan-Mehmood1/cog_Wav2Lip_COLAB_working.git",
                              "cd cog_Wav2Lip_COLAB_working && pip install -r requirements.txt"))


vol = Volume.persisted("wav2lip_volume")
stub =  modal.Stub("wav2lip")

with project_image.imports():
    # import importlib
    # import sys
    # sys.path.append("cog_Wav2Lip_COLAB_working")    
    # module_name = "cog_Wav2Lip_COLAB_working"
    
    # # Import the module dynamically
    # wav2lip = importlib.import_module(module_name)
    # import git
    import gdown
    import zipfile
    import argparse
    import math
    import os
    import platform
    import subprocess

    import cv2
    import numpy as np
    import torch
    from tqdm import tqdm

    import audio
    # # from face_detect import face_rect
    from models import Wav2Lip

    from batch_face import RetinaFace
    from time import time


@stub.cls(gpu="T4", image=project_image, volumes={"/data": vol}, container_idle_timeout=300)
class Model:
    @enter()
    def enter(self, extract_to_directory="/data"):
        # Download the necessary checkpoints
        zip_file_url = "https://drive.google.com/file/d/1_AlLfRcu-82u9Wf0U2y8A4F5MamoNQnu/view?usp=drive_link"
        zip_file_path = os.path.join(extract_to_directory, 'ckpts.zip')
        gdown.download(url=zip_file_url, output=zip_file_path, quiet=False, fuzzy=True)
        # Create the target directory if it doesn't exist
        os.makedirs(extract_to_directory, exist_ok=True)
        # Extract contents to the target directory
        with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
            zip_ref.extractall(extract_to_directory)
        # Remove the downloaded ZIP file
        os.remove(zip_file_path)
        print(f"Successfully downloaded and extracted to '{extract_to_directory}'.")
        print("\n\n\t",os.listdir(extract_to_directory),"\n\n")
        print("\n\n\t",os.listdir(),"\n\n")

        vol.commit()

    @method()
    def predict():
        print("...Hi")

@stub.function(image=project_image, volumes={"/data": vol}, gpu="T4", container_idle_timeout=300)
@web_endpoint(method="POST",label="predict")
def main():

    response = Model().predict.remote()
    return "Hi"
```

------------------------------------------

> 
> (modal) arslan@Folio-1040-G2:~/nixense_vixion/To-Do/cog_wav2lip_modal$ modal serve modal_wav2lip.py 
> ✓ Initialized. View run at https://modal.com/arslan-mehmood1/apps/ap-LqXMIgbHdlauqSsfbir7SW
> ✓ Created objects.
> ├── 🔨 Created mount /home/arslan/nixense_vixion/To-Do/cog_wav2lip_modal/modal_wav2lip.py
> ├── 🔨 Created Model.predict.
> └── 🔨 Created main => https://arslan-mehmood1--predict-dev.modal.run
> ⚡️ Serving... hit Ctrl-C to stop!
> └── Watching /home/arslan/nixense_vixion/To-Do/cog_wav2lip_modal.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/pkg/modal/_container_entrypoint.py", line 850, in <module>
>     main(container_args, client)
>   File "/pkg/modal/_container_entrypoint.py", line 805, in main
>     container_app.hydrate_function_deps(imp_fun.function, dep_object_ids)
>   File "/pkg/synchronicity/synchronizer.py", line 497, in proxy_method
>     return wrapped_method(instance, *args, **kwargs)
>   File "/pkg/synchronicity/synchronizer.py", line 398, in f_wrapped
>     res = f(*args, **kwargs)
>   File "/pkg/modal/app.py", line 325, in hydrate_function_deps
>     obj._hydrate(object_id, self._client, metadata)
>   File "/pkg/modal/object.py", line 107, in _hydrate
>     self._hydrate_metadata(metadata)
>   File "/pkg/modal/image.py", line 164, in _hydrate_metadata
>     raise exc
>   File "/pkg/modal/image.py", line 1361, in imports
>     yield
>   File "/root/modal_wav2lip.py", line 36, in <module>
>     import audio
> ModuleNotFoundError: No module named 'audio'

---------------------------------------------------------------

The audio.py is present in the repo which I cloned.

**Comment by kning** [comment]
when you clone the github repo it gets saved to `/` on the image. so i think if you add

```
import sys
sys.path.append("/cog_Wav2Lip_COLAB_working")
import audio
```
into the `project_image.imports()` clause it should work. i copied your code and ran `modal shell modal_wav2lip.py::main --cmd=python` to test it in the image itself and it seemed to work:
<img width="1506" alt="image" src="https://github.com/modal-labs/modal-examples/assets/1820651/f23c88bf-8116-4a55-aeb9-ba851c5b258f">
