### ISSUE TITLE
modal run error

### ISSUE THREAD

**Issue by ZekiJohn** [modal-labs/modal-examples#631]
I'm deployed comfy_ui and comfy_api as a package and use endpoint to run it. but I'm getting this error 

modal.exception.InvalidError: Can not run an app from within a container. Are you calling stub.run() directly? Consider using the `modal run` shell command.

https://github.com/modal-labs/modal-examples/blob/dfda5b83f3c1e937910fbb4cd7d7c5d6ee84be66/06_gpu_and_ml/comfyui/comfy_api.py#L128

Thanks

**Comment by charlesfrye** [comment]
Sounds like you adapted the code and ran into issues -- the code inside the `local_entrypoint` you're linking to can't be directly deployed on Modal itself.

We limit the issues and support on this repo and its issues to problems with the example code itself.

But we're more than happy to help you get things deployed on Modal if you post in the [Modal User Community](https://modal.com/slack) on Slack.
