### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by ZekiJohn** [modal-labs/modal-examples#640]
Hi

I'm using deployed comfy_ui.py _**(06_gpu_and_ml/comfyui/comfy_ui.py)**_

and I'm encountering unclosed client connections, potentially causing resource leaks. Issue appears during API interactions. works fine when using the browser.

<img width="633" alt="image" src="https://github.com/modal-labs/modal-examples/assets/45900838/b4d1f62a-b0be-4f8c-af12-8529594a8854">

It's worth noting that this issue arises one minute after receiving a successful response to a request.

**Comment by ekzhang** [comment]
Hi @ZekiJohn, you can disregard this message. We'll have a fix for this at some point in the near future.

The unclosed client sessions are only left behind on container shutdown, when they'll be closed anyway since the process exits. There's no resource leak.
