### ISSUE TITLE
OpenAI Compatible API

### ISSUE THREAD

**Issue by amir1m** [modal-labs/modal-examples#646]
Hello,
I would like to deploy Llama 7B and serve it using Open AI compatible REST API endpoints. Are there any examples of it?
I am aware if projects such as LiteLLM and LocalAI but not sure if/how to use them with Modal.

Thanks

**Comment by charlesfrye** [comment]
Hey @amir1m!

You can try wrapping a vLLM server in OpenAI-compatible mode with an `asgiproxy`, which is similar to what we do in our ComfyUI and Streamlit examples. There's also a working, if a bit heavy on boilerplate, version in this PR (#542).

If you have any further questions, feel free to post them in the [Modal Slack](https://modal.com/slack)!
