### ISSUE TITLE
Is there a way to get dbrx-instruct to work?

### ISSUE THREAD

**Issue by mochacat2001** [modal-labs/modal-examples#678]
Sample code would be great!

**Comment by charlesfrye** [comment]
You "should" be able to swap out Mixtral from [this example](https://github.com/vllm-project/vllm/pull/3660) with dbrx, so long as you 1) increase to 4 GPUs and 2) bump the version to [`vLLM ~= 0.4.0`](https://github.com/vllm-project/vllm/releases/tag/v0.4.0).
