### ISSUE TITLE
Deploy mistral 8x7b on modal not working properly

### ISSUE THREAD

**Issue by FotieMConstant** [modal-labs/modal-examples#682]
Hey everyone, amazing platform you guys have. Looking so much forward to using this. 

I am having issues deploying my model though, I’m kinda new to this and have been running LLMs locally on my M1 MacBook Pro, however inference is really slow with the mixtral 8x7b model which is why I am using modal.com

I can’t seem to have the model deployed following the example at [https://modal.com/docs/examples/vllm_mixtral](https://modal.com/docs/examples/vllm_mixtral)

I get suck at the level of
```bash
>>> f = modal.Function.lookup("example-tgi-Mixtral-8x7B-Instruct-v0.1", "Model.generate")
```

I’d like to access the model in inference via an api or something. 

I’d really appreciate it if someone would help out here.

PS: part of my Masters thesis

**Comment by charlesfrye** [comment]
Hi Fotie! Glad you're liking Modal.

If you check out [the next section in that example](https://modal.com/docs/examples/vllm_mixtral#coupling-a-frontend-web-application), you'll see an example of how to create a web endpoint that you can hit from other applications.

In general, we prefer to answer questions about the examples in our Slack, which I see you've joined. Please follow up there!
