### ISSUE TITLE
SDXL example times out

### ISSUE THREAD

**Issue by nikdnaik** [modal-labs/modal-examples#683]
`06_gpu_and_ml/stable_diffusion/stable_diffusion_xl.py`

Example does not work. Shows the following error:

` 22 in _process_result                                                                            │
│                                                                                                  │
│    121 │   if result.status == api_pb2.GenericResult.GENERIC_STATUS_TIMEOUT:                     │
│ ❱  122 │   │   raise FunctionTimeoutError(result.exception)                                      │
│    123 │   elif result.status != api_pb2.GenericResult.GENERIC_STATUS_SUCCESS:                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FunctionTimeoutError: Task's current input in-Q2JlyQSZ8CIYqXdqdFpaPo hit its timeout of 300s
`

**Comment by charlesfrye** [comment]
Hello Nikhil!

I wasn't able to reproduce this issue. Could you share more about it?

For example, did it occur during during the image build stage, e.g. the first time you ran the example and before you saw any outputs? If so, it's possible that you hit a slow download of the SDXL model, which can happen when the Hugging Face model servers are overloaded.
