### ISSUE TITLE
ModuleNotFoundError: No module named 'comfyui.comfy_api'

### ISSUE THREAD

**Issue by hongminpark** [modal-labs/modal-examples#829]
@kning Hi! I am following these tutorials related with comfyUI

- https://www.youtube.com/watch?v=julgiZqWLHc 
- https://modal.com/blog/comfyui-prototype-to-production

but I can't find `get_python_workflow` function. Also there's no `comfy_api.py`. 
I am getting `ModuleNotFoundError: No module named 'comfyui.comfy_api'` this error.
Something looks changed. Could you let me know the changes ?

**Comment by hongminpark** [comment]
@hongminpark I am figuring out from git commit histories and found out that you've deleted the files like `workflow_api.py`, `helpers.py` related with comfy script.
Can I know the reasont ? 
I want to run comfyui like this method in the tutorial.

**Comment by charlesfrye** [comment]
Hey @hongminpark!

We switched up this example to take advantage of new features of ComfyUI.   It's a rapidly developing library in a rapidly developing space, so things change a lot!

The updated walkthrough (text only) is here: https://modal.com/docs/examples/comfyapp

**Comment by charlesfrye** [comment]
If there are any features of the workflows from the previous version that aren't supported in this new version, please let us know by opening an issue!
