### ISSUE TITLE
Max model len for Llama 3.1 8B in vllm_inference.py is only 8096

### ISSUE THREAD

**Issue by handrew** [modal-labs/modal-examples#843]
As shown when hitting the `/models` endpoint

```
{"object":"list","data":[{"id":"meta-llama/Meta-Llama-3.1-8B-Instruct","object":"model","created":1723770563,"owned_by":"vllm","root":"meta-llama/Meta-Llama-3.1-8B-Instruct","parent":null,"max_model_len":8096,"permission":[{"id":"modelperm-7c4c5de9b37b4f76800eb2d03b845b00","object":"model_permission","created":1723770563,"allow_create_engine":false,"allow_sampling":true,"allow_logprobs":true,"allow_search_indices":false,"allow_view":true,"allow_fine_tuning":false,"organization":"*","group":null,"is_blocking":false}]}]}%
```

It should be 128K, right? Might be a VLLM thing?

**Comment by charlesfrye** [comment]
You can configure the max model length in the vllm_inference.py file! I set it conservatively to limit the size of the KV cache, which IIUC depends on the sequence length. You might need to increase the number of GPUs (N_GPU) and/or switch to A100-80s to handle longer sequences.

Let me know how it goes!

**Comment by charlesfrye** [comment]
That's done [here](https://github.com/modal-labs/modal-examples/blob/main/06_gpu_and_ml%2Fllm-serving%2Fvllm_inference.py#L147), fyi.

The GPU config is set above, in the decorator on the function.

**Comment by handrew** [comment]
🤦🏻‍♂️ my bad. Should have read the code more carefully. Appreciate the response!
