### ISSUE TITLE
Vulkan: vulkaninfo --summary does not recognize GPU

### ISSUE THREAD

**Issue by philmaas** [modal-labs/modal-examples#869]
When running `vulkaninfo --summary` it only recognizes GPU0 using the Mesa drivers.

`Devices:
========
GPU0:
        apiVersion         = 4206847 (1.3.255)
        driverVersion      = 1 (0x0001)
        vendorID           = 0x10005
        deviceID           = 0x0000
        deviceType         = PHYSICAL_DEVICE_TYPE_CPU
        deviceName         = llvmpipe (LLVM 15.0.7, 256 bits)
        driverID           = DRIVER_ID_MESA_LLVMPIPE
        driverName         = llvmpipe
        driverInfo         = Mesa 23.2.1-1ubuntu3.1~22.04.2 (LLVM 15.0.7)
        conformanceVersion = 1.3.1.1
        deviceUUID         = 6d657361-3233-2e32-2e31-2d3175627500
        driverUUID         = 6c6c766d-7069-7065-5555-494400000000`

`nvidia-smi` recognizes the GPU correctly (T4 in my case) with CUDA 12.4 and driver 550.54.15

A test docker image running on linux is able to correctly print the hosts GPU (also a T4) when running vulkaninfo --summary inside the container.
[](https://github.com/rickyjames35/vulkan_docker_test)

I'm curious to learn more from the team what the issues or restrictions might be. (nvidia-container-toolkit?)

Also if there is anyone who is trying to run rendering apps using vulkan on Modal as well.
The blender GPU rendering example is working, however it's not clear how one would be able to select the GPU device in a custom app. 

Any help would be greatly appreciated.

**Comment by charlesfrye** [comment]
Hey there!

We use the issues section of this repo to track issues with the examples themselves, and it sounds like there aren't issues there.

Would you mind re-raising this in the Modal community Slack (modal.com/slack) or over email (support@modal.com)?

Top-of-my-head answer: kernel-level device drivers live in the host, not the container. Our hosts have the NVIDIA CUDA drivers and not the Mesa drivers. Some notes [here](https://modal.com/docs/guide/cuda).
