### ISSUE TITLE
Download files from a Modal App

### ISSUE THREAD

**Issue by tusharkhot** [modal-labs/modal-examples#870]
I am running a job on Modal that creates a few files that I want to download. I am not trying to mount any local files and don't need any persistence or sharing across functions. How would I go about doing it? I have looked around the examples and documentations (Mounts, Volumes, NFS, etc) and its not really clear how to go about this.

Thanks (and please let me know if there is a more appropriate forum for such questions)

**Comment by charlesfrye** [comment]
Hello there!

We use the issues section of this repo to track issues with the examples themselves.

Would you mind re-raising this in the Modal community Slack (modal.com/slack) or over email ([support@modal.com](mailto:support@modal.com))?
