### ISSUE TITLE
add headers to all examples

### ISSUE THREAD

**Issue by charlesfrye** [modal-labs/modal-examples#884]
Some examples are just code. The code blocks are not indexed by our docs search (or external search engines!) but text and headings are. We should add headings to examples to make them more discoverable. cc @kning @yirenlu92

**Comment by yirenlu92** [comment]
I can take this on unless someone else has already started!

**Comment by charlesfrye** [comment]
There's some work already started in #885

**Comment by kning** [comment]
i'm just cleaning up 06_gpu_ml feel free to take the other folders!
