### ISSUE TITLE
how to run llama3.2 1b model ?

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [modal-labs/modal-examples#900]
using this

[06_gpu_and_ml/llm-serving/text_generation_inference.py](https://github.com/modal-labs/modal-examples/blob/main/06_gpu_and_ml/llm-serving/text_generation_inference.py)

I'm unable to get generated text correctly.
![image](https://github.com/user-attachments/assets/e1141bd3-091c-4db9-a2a3-9382e04a3333)

**Comment by charlesfrye** [comment]
Hey there!

We reserve the GitHub Issues page for issues with the examples as they are written, but this looks like an issue with the example after it has been edited.

We provide support for general use of the Modal platform in our Community Slack, https://modal.com/slack.

The short answer is that it looks like the chat template here is wrong.
