### ISSUE TITLE
App Logs example-comfyui  error

### ISSUE THREAD

**Issue by MarchiBallard** [modal-labs/modal-examples#921]
`   POST /api/prompt -> 400 Bad Request  (duration: 177.0 ms, execution: 77.7 ms)
got prompt
Failed to validate prompt for output 9:
* CheckpointLoaderSimple 4:
  - Value not in list: ckpt_name: 'None' not in []
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
   POST /api/prompt -> 400 Bad Request  (duration: 159.5 ms, execution: 52.5 ms)
got prompt
Failed to validate prompt for output 9:
* CheckpointLoaderSimple 4:
  - Value not in list: ckpt_name: 'None' not in []
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
   POST /api/prompt -> 400 Bad Request  (duration: 138.7 ms, execution: 52.0 ms)
Stopping app - unknown reason
CONNECT /ws -> 101 Switching Protocols  (duration: 55.4 s, execution: 0.0 ms)`

**Comment by kning** [comment]
this suggests to me that the checkpoint isn't properly being downloaded. are you running the latest example with no alterations?
