### ISSUE TITLE
improve model loading in comfyapp

### ISSUE THREAD

**Issue by charlesfrye** [modal-labs/modal-examples#952]
The `comfyapp` example takes many minutes to build. The download of `flux.1-schnell` in particular is very slow. I suspect that the `comfy` CLI is leaving a lot of download performance on the table (e.g. not using `hf-transfer`).

Additionally, models are downloaded into the container image. Storing a model in a Volume is just as performant as storing in an Image and avoids rebuilds. Maybe put the download call into the `local_entrypoint` and direct users to `modal run` before doing `modal serve`/`modal deploy`?

cc @kning @kramstrom

**Comment by kning** [comment]
@kramstrom do you have a link to the gist handy?

**Comment by kning** [comment]
nm i found it: https://modal.com/blog/comfyui-custom-nodes
